stages:
    - test
    - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

test:
    image: kylessg/bullet-train-nightwatch:1.1
    stage: test
    script:
        - google-chrome --version
        - node -v
        - npm i
        - if [ $CI_COMMIT_REF_NAME == "staging" ]; then export ENV=staging; echo 'Setting env to' $ENV; npm run env; fi;
        - if [ $CI_COMMIT_REF_NAME == "develop" ]; then export ENV=dev; echo 'Setting env to' $ENV; npm run env; fi;
        - if [ $CI_COMMIT_REF_NAME == "master" ]; then export ENV=prod; echo 'Setting env to' $ENV; npm run env; fi;
        - npm run test
    only:
        - master
        - staging

build-dockerhub:
  stage: deploy
  tags:
    - flagsmith-shell-runner
  script:
    - if [ "$CI_COMMIT_REF_NAME" == "master" ]; then IMAGE_TAG="latest"; elif [ "$CI_COMMIT_REF_NAME" == "develop" ]; then IMAGE_TAG="develop"; else IMAGE_TAG=$CI_COMMIT_TAG; fi
    - echo $CI_COMMIT_REF_NAME > $CI_PROJECT_DIR/CI_COMMIT_REF_NAME
    - echo $CI_COMMIT_SHA > $CI_PROJECT_DIR/CI_COMMIT_SHA
    - echo $IMAGE_TAG > $CI_PROJECT_DIR/IMAGE_TAG
    - docker login --username $DOCKER_HUB_PUSH_USERNAME_SHELL_RUNNER -p $DOCKER_HUB_PUSH_PASSWORD_SHELL_RUNNER
    - docker build -t flagsmith/flagsmith-frontend:$IMAGE_TAG -f Dockerfile .
    - docker push flagsmith/flagsmith-frontend:$IMAGE_TAG
  only:
    - master
    - tags
    - develop

deploymaster:
    image: kylessg/bullet-train-gcloud:1.0
    stage: deploy
    script:
        - npm i
        - export ENV=prod; npm run env
        - npm run dotenv
        - npm run bundle
        - echo $DEPLOY_KEY_FILE_PROD > /tmp/$CI_PIPELINE_ID.json
        - gcloud auth activate-service-account --key-file /tmp/$CI_PIPELINE_ID.json
        - gcloud config set project bullet-train-front-end-prod
        - gcloud app deploy
    only:
        - master

deploystaging:
  image: kylessg/bullet-train-gcloud:1.0
  stage: deploy
  script:
    - npm i
    - export ENV=staging; npm run env
    - npm run dotenv
    - npm run bundlestaging
    - echo $DEPLOY_KEY_FILE_STAGING > /tmp/$CI_PIPELINE_ID.json
    - gcloud auth activate-service-account --key-file /tmp/$CI_PIPELINE_ID.json
    - gcloud config set project bullet-train-front-end-staging
    - gcloud app deploy
  only:
    - staging

deploydevelop:
    image: kylessg/bullet-train-gcloud:1.0
    stage: deploy
    script:
        - npm i
        - export ENV=dev; npm run env
        - npm run dotenv
        - npm run bundledev
        - echo $DEPLOY_KEY_FILE_DEV > /tmp/$CI_PIPELINE_ID.json
        - gcloud auth activate-service-account --key-file /tmp/$CI_PIPELINE_ID.json
        - gcloud config set project bullet-train-front-end-dev
        - gcloud app deploy
    only:
        - develop
